"""
Pythia Diff Report

Computes the difference between two scans for the same domain.
Used by --diff SCAN_ID (or --diff last) CLI flag.

Author: Rodney Dhavid Jimenez Chacin (rodhnin)
License: MIT
"""

from typing import Dict, Any, Optional, List

from .logging import get_logger

logger = get_logger(__name__)


def _finding_summary(f: Dict[str, Any]) -> Dict[str, str]:
    """Return a minimal finding dict suitable for diff output.

    Accepts both DB rows (finding_code key) and in-memory finding dicts (id key).
    """
    return {
        'id':       f.get('finding_code') or f.get('id', ''),
        'title':    f.get('title', ''),
        'severity': f.get('severity', ''),
    }


def compute_diff(
    db,
    current_scan_id: int,
    ref_scan_id_or_last: str,
    domain: str,
    current_findings: Optional[List[Dict[str, Any]]] = None,
) -> Optional[Dict[str, Any]]:
    """
    Compare the current scan's findings against a reference scan.

    Args:
        db: Database instance
        current_scan_id: ID of the scan just completed
        ref_scan_id_or_last: Scan ID string or "last" for the most recent prior scan
        domain: Domain being scanned (used for "last" lookup)

    Returns:
        diff dict with ref_scan_id, ref_date, new, fixed, persisting lists
        or None if the reference scan cannot be found.
    """
    # Resolve "last" to an actual scan_id
    if str(ref_scan_id_or_last).lower() == 'last':
        ref_scan = _get_last_completed_scan(db, domain, exclude_id=current_scan_id)
        if not ref_scan:
            logger.warning(f"No prior completed scan found for domain '{domain}' to diff against")
            return None
        ref_scan_id = ref_scan['scan_id']
    else:
        try:
            ref_scan_id = int(ref_scan_id_or_last)
        except (ValueError, TypeError):
            logger.error(f"Invalid diff scan ID: {ref_scan_id_or_last!r}")
            return None
        ref_scan = db.get_scan(ref_scan_id)
        if not ref_scan:
            logger.error(f"Reference scan ID {ref_scan_id} not found in database")
            return None

    if ref_scan_id == current_scan_id:
        logger.warning("Reference scan is the same as current scan — diff skipped")
        return None

    # Validate that the reference scan used the same tool
    current_scan = db.get_scan(current_scan_id)
    if current_scan and ref_scan.get('tool') != current_scan.get('tool'):
        ref_tool = ref_scan.get('tool', 'unknown')
        cur_tool = current_scan.get('tool', 'unknown')
        logger.error(
            f"Cannot diff scans from different tools: "
            f"current={cur_tool} vs reference={ref_tool}. "
            f"Use a reference scan generated by '{cur_tool}'."
        )
        return None

    logger.info(f"Computing diff: scan {current_scan_id} vs scan {ref_scan_id}")

    # Use in-memory findings if provided (not yet saved to DB at this point in scan flow),
    # otherwise fall back to DB lookup (e.g. when called externally after scan completion).
    if current_findings is None:
        current_findings = db.get_findings(current_scan_id)
    ref_findings = db.get_findings(ref_scan_id)

    def _code(f: Dict[str, Any]) -> str:
        """Normalize finding code key (DB rows use 'finding_code', in-memory use 'id')."""
        return f.get('finding_code') or f.get('id', '')

    # Index by finding_code for O(1) lookups
    current_codes = {_code(f) for f in current_findings}
    ref_codes     = {_code(f) for f in ref_findings}

    new_codes        = current_codes - ref_codes
    fixed_codes      = ref_codes - current_codes
    persisting_codes = current_codes & ref_codes

    # Build output lists (sorted by id for deterministic output)
    new_findings = sorted(
        [_finding_summary(f) for f in current_findings if _code(f) in new_codes],
        key=lambda x: x['id']
    )
    fixed_findings = sorted(
        [_finding_summary(f) for f in ref_findings if _code(f) in fixed_codes],
        key=lambda x: x['id']
    )
    persisting_findings = sorted(
        [_finding_summary(f) for f in current_findings if _code(f) in persisting_codes],
        key=lambda x: x['id']
    )

    current_mode = current_scan.get('mode', '') if current_scan else ''
    ref_mode = ref_scan.get('mode', '')
    mode_mismatch = bool(current_mode and ref_mode and current_mode != ref_mode)

    if mode_mismatch:
        logger.warning(
            f"Mode mismatch in diff: current scan is '{current_mode}' but reference "
            f"scan #{ref_scan_id} was '{ref_mode}'. 'Fixed' findings may include checks "
            f"that were not performed in '{current_mode}' mode — not necessarily remediated."
        )

    diff = {
        'ref_scan_id': ref_scan_id,
        'ref_date': ref_scan.get('started_at') or ref_scan.get('finished_at', ''),
        'ref_target': ref_scan.get('target_url', domain),
        'ref_mode': ref_mode,
        'current_mode': current_mode,
        'mode_mismatch': mode_mismatch,
        'new': new_findings,
        'fixed': fixed_findings,
        'persisting': persisting_findings,
    }

    logger.info(
        f"Diff result: {len(new_findings)} new, "
        f"{len(fixed_findings)} fixed, "
        f"{len(persisting_findings)} persisting"
    )
    return diff


def _get_last_completed_scan(db, domain: str, exclude_id: int) -> Optional[Dict[str, Any]]:
    """Return the most recent completed scan for domain, excluding exclude_id."""
    scans = db.list_scans(tool='pythia', domain=domain, limit=50)
    for scan in scans:
        if scan['scan_id'] == exclude_id:
            continue
        if scan['status'] == 'completed':
            return scan
    return None
